### PR TITLE
Beating BLAS for euclidian distance kernel

### PR DESCRIPTION
**Pull request by peterbell10**
With some tweaking, I was able to optimise your distance kernel a bit further so  it beats BLAS in many more cases. I tested every number of dimensions from 1 to 64 with AtsushiSakai's knn-query benchmark:

```python
In [1]: import numpy as np 
   ...: from scipy.spatial import cKDTree 
   ...: for ndim in range(1, 65): 
   ...:     np.random.seed(20) 
   ...:     vehicle_coords = np.random.random((50, ndim)) 
   ...:     np.random.seed(21701) 
   ...:     obstacle_coords = np.random.random((77500, ndim)) 
   ...:     t = cKDTree(obstacle_coords) 
   ...:     to = %timeit -oq t.query(vehicle_coords, k=20) 
   ...:     print(f'ndim={ndim}, {to.best*1e3:.3f} ms, {to.average*1e3:.3f} ms')
```

On my machine, the new vecorized version was faster than MKL BLAS for all sizes and even 10x faster at 14 dimensions. The scalar version is also around 1-2x faster up until 50 dimensions, and that is without enabling auto-vectorisation.

An important point I found is that `std::fma` actually makes the code slower. I'm assuming the `-march` setting isn't high enough to emit actual fma instructions and so we end up with a software emulation.

### CODE REVIEW

**Comment by sturlamolden** [comment]
I have been tweaking too :) fma does indeed make it slower. I even found an explanation why this is the case. The advantage of fma on x86/amd64 is apparently smaller rounding error.

I also found that SSE3 tends to be faster than AVX for some reason, at least on my older laptop. We don't compile SciPy for AVX AFAIK, but it persists even when I pass -mavx to the compiler.

**Comment by sturlamolden** [comment]
Currently the fastest I have produced for GCC is this

```C++
    typedef double vec2d __attribute__ ((vector_size (2*sizeof(double)))); 

    inline vec2d
    _kernel_2d(const double * __restrict__ u, const double * __restrict__ v)
    {
        vec2d _u = {u[0], u[1]};
        vec2d _v = {v[0], v[1]};
        return _u - _v;
    }
    
    inline vec2d
    _kernel_2d_pad(const double * __restrict__ u, const double * __restrict__ v)
    {
        vec2d _u = {*u, 0.0};
        vec2d _v = {*v, 0.0};
        return _u - _v;
    }
    
    
    inline double
    _sqeuclidean(const double * __restrict__ u, const double * __restrict__ v, const ckdtree_intp_t n)
    {
        double s = 0.0;
        ckdtree_intp_t i;
        const ckdtree_uintp_t un = static_cast<ckdtree_uintp_t>(n);
        
        switch(un) {
        
            case 0:
            break;
            
            case 1:
            {
                double d = *u - *v;
                s = d * d;
            }
            break;
            
            case 2:
            {
                vec2d acc = _kernel_2d(u,v);
                s = acc[0] + acc[1];
            }
            break;
            
            case 3:
            {
                vec2d acc = _kernel_2d(u,v) 
                          + _kernel_2d_pad(u+2,v+2);
                s = acc[0] + acc[1];
            }
            break;
            
            case 4:
            { 
                vec2d acc = _kernel_2d(u,v) 
                          + _kernel_2d(u+2,v+2);
                s = acc[0] + acc[1];
            }
            break;
            
            case 5:
            { 
                vec2d acc = _kernel_2d(u,v) 
                          + _kernel_2d(u+2,v+2) 
                          + _kernel_2d_pad(u+4,v+4);
                s = acc[0] + acc[1];
            }
            break;
            
            case 6:
            {
                vec2d acc = _kernel_2d(u,v) 
                          + _kernel_2d(u+2,v+2) 
                          + _kernel_2d(u+4,v+4);
                s = acc[0] + acc[1];
            }
            break;
            
            case 7:
            {
                vec2d acc = _kernel_2d(u,v) 
                          + _kernel_2d(u+2,v+2) 
                          + _kernel_2d(u+4,v+4);
                          + _kernel_2d_pad(u+6,v+6);
                s = acc[0] + acc[1];
            }
            break;
            
            default:
            {
                vec2d acc;
                ckdtree_intp_t i;
                for (i = 0; i < n/8; i += 8) {
                    acc += _kernel_2d(u,v) 
                          + _kernel_2d(u+2,v+2) 
                          + _kernel_2d(u+4,v+4);
                          + _kernel_2d(u+6,v+6);
                }
                s = acc[0] + acc[1];
                if (i < n) s += _sqeuclidean10(u+i, v+i, n-i);
            }   
        }
            
        return s;
    }
```

But it is not much better than the much simpler

```
   inline double
    _sqeuclidean(const double * __restrict__ u, const double * __restrict__ v, const ckdtree_intp_t n)
    {
        typedef double vec2d __attribute__ ((vector_size (2*sizeof(double)))); 
        double s = 0.0;
        ckdtree_intp_t i;
        vec2d acc = {0., 0.};
        for (i = 0; i < n/2; i += 2) {
            vec2d _u = {u[i], u[i + 1]};
            vec2d _v = {v[i], v[i + 1]};
            vec2d diff = _u - _v;
            acc += diff * diff;
        }
        s = acc[0] + acc[1];
        if (n % 2) {
            double d = u[i] - v[i];
            s += d * d;
        }
        return s;
    }
```

BLAS is definately going out. That one never helps.

I will try your code too and see how it compares :)

**Comment by sturlamolden** [comment]
And I thought the AVX issue might be related to alignment, so I wrote code that creates an n x d numpy array wherre each row is 32-byte aligned. But that did not help either...

```Cython
cimport numpy as cnp

from cpython cimport Py_buffer

cdef extern from *:
    void* PyMem_Calloc(size_t n, size_t elsize)
    void PyMem_Free(void *p)

cdef class AlignedBuffer:
    
    cdef Py_ssize_t shape[2]
    cdef Py_ssize_t strides[2]
    cdef void *buf
    cdef char *aligned_buf
    cdef Py_ssize_t offs
    cdef Py_ssize_t align
    cdef object buf_format

    def __cinit__(self, Py_ssize_t n, Py_ssize_t d, Py_ssize_t align=32):
        
        cdef:
            Py_ssize_t db, rowsize, izp
            
        # format is a NUL terminated string:
        # const char *s = "d"
        self.buf_format = "d\0".encode("utf-8")
        
        # find the padded row size that allows all
        # rows to be alined at `align` bytes
        self.align = align
        db = d*sizeof(double)
        rowsize = db - (db % align) + align
        
        self.shape[0] = n
        self.shape[1] = d
        
        # Stride 1 is the distance, in bytes, between two items in a row;
        # this is the distance between two adjacent items in the vector.
        # Stride 0 is the distance between the first elements of adjacent rows.
        self.strides[0] = rowsize
        self.strides[1] = sizeof(double)
        
        # allocate an array of bytes large enough to
        # store the array with alined rows
        self.buf = PyMem_Calloc(n * rowsize + align, 1)
        if (self.buf == NULL): raise MemoryError()
        
        # find out the offset needed for `align` byte alignment
        izp = <cnp.uintp_t> self.buf
        self.offs = izp % align
        self.aligned_buf = self.offs + <char*> self.buf
        
    def __dealloc__(self):
        if self.buf:
            PyMem_Free(self.buf)
            self.buf = NULL

    def __getbuffer__(self, Py_buffer *buffer, int flags):
        
        buffer.buf = self.aligned_buf
        buffer.format = <char*> self.buf_format
        buffer.internal = NULL                  # see References
        buffer.itemsize = sizeof(double)
        buffer.len = self.shape[0] * self.shape[1] * sizeof(double)   # product(shape) * itemsize
        buffer.ndim = 2
        buffer.obj = self
        buffer.readonly = 0
        buffer.shape = self.shape
        buffer.strides = self.strides
        buffer.suboffsets = NULL                # for pointer arrays only

    def __releasebuffer__(self, Py_buffer *buffer):
        pass


def aligned_rows(cnp.intp_t n, cnp.intp_t d, align=32):
    """ creates an array where each row is aligned to a specific boundary """
    return np.asarray(AlignedBuffer(n, d, align=align))
    
    
def has_aligned_rows(cnp.float64_t[:,:] x, align=32):
    cdef:
        cnp.intp_t i, n
        cnp.uintp_t addr, ialign
    ialign = <cnp.uintp_t> align
    n = x.shape[0]
    for i in range(n):
        addr = <cnp.uintp_t> (<void*> &x[i,0])
        if addr % ialign:
            return False
    return True

```

**Comment by sturlamolden** [comment]
It seems that for low dimensional cases (up to 3d), your scalar version is the faster, even when using GCC. From 4 an up my faster version seems to be the better. 

So I merged the 0d to 3d switch cases from your scalar version into my vector version, which gives me this which gives the overall better performance on my computer thus far.

I have no idea why the scalar version is better in low dimensions, but at least on my computer it is.


```C++

    typedef double vec2d __attribute__ ((vector_size (2*sizeof(double))))
    #pragma GCC optimize("tree-vectorize")
    #pragma GCC optimize("unsafe-math-optimizations")
    #pragma GCC optimize("unroll-loops")

inline vec2d
    _kernel_2d(const double * __restrict__ u, const double * __restrict__ v)
    {
        vec2d _u = {u[0], u[1]};
        vec2d _v = {v[0], v[1]};
        return _u - _v;
    }
    
    inline vec2d
    _kernel_2d_pad(const double * __restrict__ u, const double * __restrict__ v)
    {
        vec2d _u = {*u, 0.0};
        vec2d _v = {*v, 0.0};
        return _u - _v;
    }
    
    
    inline double
    _sqeuclidean10(const double * __restrict__ u, const double * __restrict__ v, const ckdtree_intp_t n)
    {
        double s = 0.0;
        ckdtree_intp_t i;
        const ckdtree_uintp_t un = static_cast<ckdtree_uintp_t>(n);
        
        switch(un) {
            case 0: return 0.0;
            case 1:
            {
                double d = u[0] - v[0];
                return d*d;
            }
            case 2:
            {
                double diff[2] = {u[0] - v[0],
                                  u[1] - v[1]};
                return diff[0] * diff[0] + diff[1] + diff[1];
            }
            case 3:
            {
                double diff[3] = {u[0] - v[0],
                                  u[1] - v[1],
                                  u[2] - v[2]};
                return (diff[0] * diff[0] +
                        diff[1] * diff[1] +
                        diff[2] * diff[2]);
            }
         
            
            case 4:
            { 
                vec2d acc = _kernel_2d(u,v) 
                          + _kernel_2d(u+2,v+2);
                s = acc[0] + acc[1];
            }
            break;
            
            case 5:
            { 
                vec2d acc = _kernel_2d(u,v) 
                          + _kernel_2d(u+2,v+2) 
                          + _kernel_2d_pad(u+4,v+4);
                s = acc[0] + acc[1];
            }
            break;
            
            case 6:
            {
                vec2d acc = _kernel_2d(u,v) 
                          + _kernel_2d(u+2,v+2) 
                          + _kernel_2d(u+4,v+4);
                s = acc[0] + acc[1];
            }
            break;
            
            case 7:
            {
                vec2d acc = _kernel_2d(u,v) 
                          + _kernel_2d(u+2,v+2) 
                          + _kernel_2d(u+4,v+4);
                          + _kernel_2d_pad(u+6,v+6);
                s = acc[0] + acc[1];
            }
            break;
            
            default:
            {
                vec2d acc;
                ckdtree_intp_t i;
                for (i = 0; i < n/8; i += 8) {
                    acc += _kernel_2d(u,v) 
                          + _kernel_2d(u+2,v+2) 
                          + _kernel_2d(u+4,v+4);
                          + _kernel_2d(u+6,v+6);
                }
                s = acc[0] + acc[1];
                if (i < n) s += _sqeuclidean10(u+i, v+i, n-i);
            }   
        }
            
        return s;
    }
```

**Comment by peterbell10** [comment]
I think there's a mistake in your vector loops
```cpp
for (i = 0; i < n/8; i += 8) {
```
Shouldn't it be `i + 8 <= n`?

**Comment by sturlamolden** [comment]
Indeed. Or equivalently ```for (i = 0; i < n-7; i += 8)```. 

We have this bug silently in SciPy master as well in the ```for (i = 0; i < n/4; i += 4)``` loop. It should be  ```for (i = 0; i < n-3; i += 4)```. From a numerical point of view it does not do any harm, but the loop is still bogus.

**Comment by sturlamolden** [comment]
The compiler is too smart for its own good. For example the scalar case for n=2 always fails. As do your vector versions for n>6. Even more, the scalar cases for n>6 fails now and then  and sometimes segfaults. As the scalar code for n=2 obviously is correct, I think it is the compiler that is causing the CI failure. Consequently I have uploaded a simpler version.

For example changing
```
double diff[2] = {u[0] - v[0], u[1] - v[1]};
return diff[0] * diff[0] + diff[1] + diff[1];
```
Into
```
const double d0 = u[0] - v[0];
const double d1 = u[1] - v[1];
return (d0*d0) + (d1*d1);
```
gives correct results on my computer. Why? I have no idea what the compiler is thinking here...

**Comment by peterbell10** [comment]
>return diff[0] * diff[0] + diff[1] + diff[1];

Oops, there is a typo. That is doing `+ diff[1] * 2`.

Can you say more about the other incorrect results you were seeing? Maybe there are some other small errors.

**Comment by sturlamolden** [comment]
I found the typo in your simd version:

```
constexpr int ilp_factor = 2;
    vec2d acc[ilp_factor]{{0.}};
    ckdtree_intp_t i;
    for (i = 0; i + 2 * ilp_factor <= n; i += 2 * ilp_factor) {
        #pragma unroll
        for (int k = 0; k < ilp_factor; ++k) {
            const double * uk = &u[i + 2 * ilp_factor * k];
            vec2d _u = { uk[0], uk[1] };

            const double * vk = &v[i + 2 * ilp_factor * k];
            vec2d _v = { vk[0], vk[1] };

            auto diff = _u - _v;
            acc[k] += diff * diff;
        }
    }
```

It should have:
```const double * uk = &u[i + 2 * k];```
```const double * vk = &v[i + 2 * k];```

**Comment by peterbell10** [comment]
Good catch.

I guess this means cKDTree doesn't really test for large numbers of dimensions as that didn't trigger the test suite to fail for me at all.

**Comment by sturlamolden** [comment]
It also passed the SciPy testsuite, so I will add another testcase for it.

**Comment by sturlamolden** [comment]
I  noticed your scalar version is faster for n < 7. So it made me wonder what the compiler could do. At least with GCC 8.2 this is this works equally well

```
template <unsigned int n>
struct sqeucdist_meta
{
    double result;
    sqeucdist_meta(const double * __restrict__ u, 
                   const double * __restrict__ v)
    {
        result = 0.0;        
        #pragma unroll
        for (unsigned int i=0; i<n; i++) {
            double d = u[i] - v[i];
            result += d*d;
        }
    }
};
```

**Comment by peterbell10** [comment]
Are you compiling with auto-vectorisation on?

**Comment by sturlamolden** [comment]
Good question. Here I have just done whatever SciPy distutils does by default. And I do not see any difference when these are commented out:
```
#pragma GCC optimize("tree-vectorize") 
#pragma GCC optimize("unsafe-math-optimizations")
#pragma GCC optimize("unroll-loops")
```
I the PR I added template specializations for smaller dimensions though. I also tried Blitz++ style template recursion, but at least above 8 dimensions and up it was not as good as a fized size loop.

**Pull request merged**
